### ISSUE TITLE
Can you add support for 5.99?

### ISSUE THREAD

**Issue by HaydenHu** [ian-ross/kicad-plugins#4] opened 2021-08-07 11:35 UTC
I like this plug-in very much. Thank you very much for your work! However, it does not support 5.99 at present, and the new schematic API is likely not to be added. However, V6 cannot be released for a long time, and the release date is still unpredictable. I hope you can increase your support for 5.99

**Comment by ian-ross** [comment] 2021-08-08 20:30
This is a duplicate of #3. I really don't want to do this, as I'm not using 5.99 myself. I've not been keeping up with what's happening with the current development of v6, and was definitely planning to wait for the schematic API to be released before updating this. As I said on the other issue, I'm happy to accept PRs to handle this. If you're really impatient, @wm93 has some changes in a private repository that might do the job for you — you could ask them if you can use their code.

But I **will** update the plugin when v6 is released with the new schematic API!

**Comment by ian-ross** [comment] 2021-09-27 10:40
@lvsoft has very kindly added support for the new schematic file format.

**Closed as completed by ian-ross** 2021-09-27 10:40 UTC
